auto update for package plex-media-server

diff --git a/archlinuxcn/plex-media-server/plex-media-server.install b/archlinuxcn/plex-media-server/plex-media-server.install
--- a/archlinuxcn/plex-media-server/plex-media-server.install
+++ b/archlinuxcn/plex-media-server/plex-media-server.install
@@ -1,6 +1,12 @@
-post_install() {
-  systemd-sysusers plex.conf
-  [[ -d /var/lib/plex ]] || install -dm 750 -o plex -g plex /var/lib/plex
+post_upgrade() {
+  # The plex user's home directory needs to change too.
+  if [[ "$( getent passwd plex | cut -d: -f6 )" != "/usr/lib/plexmediaserver" ]]; then
+    usermod -d /usr/lib/plexmediaserver plex
+    if [[ $? -ne 0 ]]; then
+      echo "Could not change plex users home directory."
+      echo "Run: sudo systemctl stop plexmediaserver ; sudo usermod -d /usr/lib/plexmediaserver plex ; sudo systemctl start plexmediaserver"
+    fi
+  fi
 }
 
 # vim: ts=2 sw=2 et:
