auto update for package fcitx-sogoupinyin

diff --git a/fcitx-sogoupinyin/sogou-autostart b/fcitx-sogoupinyin/sogou-autostart
--- a/fcitx-sogoupinyin/sogou-autostart
+++ b/fcitx-sogoupinyin/sogou-autostart
@@ -1,6 +1,15 @@
 #!/bin/sh
 
-# sleep for a little while to avoid duplicate startup
-sleep 10
+# Wait for fcitx to startup
+for i in $(seq 30); do
+  if fcitx-remote &> /dev/null; then
+    sogou-qimpanel
+    echo 'sogou-qimpanel started'
+    exit
+  else
+    sleep 1
+  fi
+done
 
-sogou-qimpanel
+echo 'sogou-qimpanel failed to start: fcitx not running'
+exit 1
