[arm-linux-gnueabihf-gcc] update

diff --git a/arm-linux-gnueabihf-gcc/PKGBUILD b/arm-linux-gnueabihf-gcc/PKGBUILD
--- a/arm-linux-gnueabihf-gcc/PKGBUILD
+++ b/arm-linux-gnueabihf-gcc/PKGBUILD
@@ -2,32 +2,33 @@
 # Maintainer: Erico Nunes <nunes dot erico at gmail>
 
 _target="arm-linux-gnueabihf"
-pkgname=${_target}-gcc
-pkgver=4.9.2
-_pkgver=4.9
-_islver=0.12.2
-_cloogver=0.18.1
-pkgrel=4
-_snapshot=4.9-20150204
+pkgbase=${_target}-gcc
+_pkgname=(gcc gcc-libs gcc-fortran
+          gcc-objc
+          # gcc-go
+         )
+pkgver=5.2.0
+_pkgver=5
+_islver=0.14.1
+pkgrel=1
+#_snapshot=5-20150623
 pkgdesc="The GNU Compiler Collection (${_target})"
 arch=(i686 x86_64)
 license=('GPL' 'LGPL' 'FDL' 'custom')
 url="http://gcc.gnu.org"
-depends=("${_target}-binutils" "${_target}-glibc" 'libmpc' 'elfutils')
+depends=("${_target}-binutils>=2.25" "${_target}-glibc" 'libmpc' 'elfutils')
 options=('!buildflags' '!libtool' '!emptydirs' 'zipman' 'docs'
          '!strip' 'staticlibs')
-conflicts=("${_target}-gcc-stage1" "${_target}-gcc-stage2")
-replaces=("${_target}-gcc-stage1" "${_target}-gcc-stage2")
-provides=("${_target}-gcc-stage1=${pkgver}" "${_target}-gcc-stage2=${pkgver}")
 source=(
-  #ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
-  ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
+  ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
+  # ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
   http://isl.gforge.inria.fr/isl-${_islver}.tar.bz2
-  http://www.bastoul.net/cloog/pages/download/cloog-${_cloogver}.tar.gz
-)
-md5sums=('5a59c19c4ff7acd3db7f8d94843f7f85'
-         'e039bfcfb6c2ab039b8ee69bf883e824'
-         'e34fca0540d840e5d0f6427e98c92252')
+  pr66035.patch
+  0001-ARMv5-disable-LDRD-STRD.patch)
+md5sums=('a51bcfeb3da7dd4c623e27207ed43467'
+         '118d1a379abf7606a3334c98a8411c79'
+         '5b980076cd5fcbc3aff6014f306282dd'
+         '924a9bcdd7852410667f04ce18c305d7')
 
 if [ -n "${_snapshot}" ]; then
     _basedir=gcc-${_snapshot}
@@ -40,9 +41,8 @@ _libdir="usr/lib/gcc/${_target}/$pkgver"
 prepare() {
   cd ${_basedir}
 
-  # link isl/cloog for in-tree builds
-  ln -s ../isl-${_islver} isl
-  ln -s ../cloog-${_cloogver} cloog
+  # link isl for in-tree builds
+  ln -sf ../isl-${_islver} isl
 
   # Do not run fixincludes
   sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
@@ -52,14 +52,46 @@ prepare() {
   # hack! - some configure tests for header files using "$CPP $CPPFLAGS"
   sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {libiberty,gcc}/configure
 
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66035
+  patch -p1 -i ../pr66035.patch
+
   mkdir -p "${srcdir}"/gcc-build
+
+  # Disable LDRD/STRD on ARMv5 (64-bit alignment issues)
+  patch -p1 -i ../0001-ARMv5-disable-LDRD-STRD.patch
+
+  rm -rf "${srcdir}/bin"
+  mkdir -p "${srcdir}/bin"
+  for c in cc c++ gcc g++; do
+    cat > "${srcdir}/bin/arm-linux-gnueabihf-${c}" <<EOF
+#!/bin/bash
+exec /usr/bin/arm-linux-gnueabihf-${c} -Wl,-rpath-link,/usr/arm-linux-gnueabihf/lib "\$@"
+EOF
+    chmod +x "${srcdir}/bin/arm-linux-gnueabihf-${c}"
+  done
+  # Try to make gccgo compilation happy
+  cat > "${srcdir}/bin/arm-linux-gnueabihf-ld" <<EOF
+#!/bin/bash
+exec /usr/bin/arm-linux-gnueabihf-ld -rpath-link /usr/arm-linux-gnueabihf/lib "\$@"
+EOF
+  chmod +x "${srcdir}/bin/arm-linux-gnueabihf-ld"
+}
+
+setup_env() {
+  export PATH="${srcdir}/bin:${PATH}"
+  export CFLAGS="-O2"
+  export CXXFLAGS="-O2"
+  export CPP=/usr/bin/cpp
+  export CXXCPP=/usr/bin/cpp
 }
 
 build() {
+  setup_env
+
   cd gcc-build
 
-  export CFLAGS="-O2"
-  export CXXFLAGS="-O2"
+  # using -pipe causes spurious test-suite failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=48565
 
   ../${_basedir}/configure \
      --prefix=/usr \
@@ -71,7 +103,7 @@ build() {
      --with-build-sysroot=/usr/${_target} \
      --with-as=/usr/bin/${_target}-as \
      --with-ld=/usr/bin/${_target}-ld \
-     --enable-languages=c,c++,fortran \
+     --enable-languages=c,c++,fortran,lto,objc,obj-c++ \
      --enable-shared \
      --enable-threads=posix \
      --enable-__cxa_atexit \
@@ -81,11 +113,11 @@ build() {
      --disable-libssp \
      --enable-gnu-unique-object \
      --enable-linker-build-id \
-     --enable-cloog-backend=isl \
      --enable-lto \
      --enable-plugin \
      --enable-install-libiberty \
      --with-linker-hash-style=gnu \
+     --enable-gnu-indirect-function \
      --disable-multilib \
      --disable-werror \
      --enable-checking=release \
@@ -93,19 +125,19 @@ build() {
      --with-float=hard \
      --enable-interwork \
      --enable-addons
-  make all-gcc all-target-libgcc all-target-libstdc++-v3
 
   make
 }
 
-package() {
-  export CFLAGS="-O2"
-  export CXXFLAGS="-O2"
+package_gcc-libs() {
+  setup_env
+  pkgdesc="Runtime libraries shipped by GCC (${_target})"
+  depends=("${_target}-glibc")
 
   cd gcc-build
 
-  # gcc libs
   make -C ${_target}/libgcc DESTDIR="${pkgdir}" install-shared
+  rm "${pkgdir}/${_libdir}/libgcc_eh.a"
 
   for lib in libatomic \
              libgfortran \
@@ -117,54 +149,128 @@ package() {
     make -C $_target/$lib DESTDIR="${pkgdir}" install-toolexeclibLTLIBRARIES
   done
 
-  # gcc
+  make -C $_target/libobjc DESTDIR="${pkgdir}" install-libs
+}
+
+package_gcc() {
+  setup_env
+  pkgdesc="The GNU Compiler Collection - C and C++ frontends (${_target})"
+  depends=("${_target}-gcc-libs=$pkgver-$pkgrel"
+           "${_target}-binutils>=2.25" 'libmpc')
+  conflicts=("${_target}-gcc-stage1" "${_target}-gcc-stage2")
+  replaces=("${_target}-gcc-stage1" "${_target}-gcc-stage2")
+  provides=("${_target}-gcc-stage1=${pkgver}" "${_target}-gcc-stage2=${pkgver}")
+
+  cd gcc-build
+
   make -C gcc DESTDIR="${pkgdir}" install-driver install-cpp install-gcc-ar \
        c++.install-common install-headers install-plugin install-lto-wrapper
+
+  # install -m755 -t "$pkgdir/usr/bin/" gcc/gcov{,-tool}
+  install -m755 -t "$pkgdir/${_libdir}/" gcc/{cc1,cc1plus,collect2,lto1}
+
   make -C $_target/libgcc DESTDIR="${pkgdir}" install
+  rm "${pkgdir}"/usr/${_target}/lib/libgcc_s.so*
 
   make -C $_target/libstdc++-v3/src DESTDIR="${pkgdir}" install
   make -C $_target/libstdc++-v3/include DESTDIR="${pkgdir}" install
   make -C $_target/libstdc++-v3/libsupc++ DESTDIR="${pkgdir}" install
-  make -C $_target/libstdc++-v3/python DESTDIR="${pkgdir}" install
+
+  rm "${pkgdir}"/usr/${_target}/lib/libstdc++.*
 
   make DESTDIR="${pkgdir}" install-fixincludes
   make -C gcc DESTDIR="${pkgdir}" install-mkheaders
-  make -C lto-plugin DESTDIR="${pkgdir}" install
 
-  make -C $_target/libgomp DESTDIR=${pkgdir} install-nodist_toolexeclibHEADERS \
-    install-nodist_libsubincludeHEADERS
-  make -C $_target/libitm DESTDIR=${pkgdir} install-nodist_toolexeclibHEADERS
-  make -C $_target/libquadmath DESTDIR=${pkgdir} install-nodist_libsubincludeHEADERS
-  make -C $_target/libsanitizer DESTDIR=${pkgdir} install-nodist_toolexeclibHEADERS
-  make -C $_target/libsanitizer/asan DESTDIR=${pkgdir} install-nodist_toolexeclibHEADERS
+  make -C lto-plugin DESTDIR="${pkgdir}" install
+  # install -dm755 "${pkgdir}"/usr/lib/bfd-plugins/
+  # ln -s /usr/lib/gcc/$_target/${pkgver}/liblto_plugin.so \
+  #    "${pkgdir}"/usr/lib/bfd-plugins/
+
+  make -C $_target/libgomp DESTDIR="${pkgdir}" \
+       install-nodist_toolexeclibHEADERS install-nodist_libsubincludeHEADERS
+  make -C $_target/libitm DESTDIR="${pkgdir}" install-nodist_toolexeclibHEADERS
+  make -C $_target/libquadmath DESTDIR="${pkgdir}" \
+       install-nodist_libsubincludeHEADERS
+  make -C $_target/libsanitizer DESTDIR="${pkgdir}" \
+       install-nodist_toolexeclibHEADERS
+  make -C $_target/libsanitizer/asan DESTDIR="${pkgdir}" \
+       install-nodist_toolexeclibHEADERS
 
   make -C libiberty DESTDIR="${pkgdir}" install
   mkdir -p "${pkgdir}"/usr/${_target}/include
   mv "${pkgdir}"/usr/include/libiberty "${pkgdir}"/usr/${_target}/include
   # install PIC version of libiberty
-  install -m644 "${srcdir}"/gcc-build/libiberty/pic/libiberty.a "${pkgdir}"/usr/${_target}/lib
+  install -m644 "${srcdir}"/gcc-build/libiberty/pic/libiberty.a \
+          "${pkgdir}"/usr/${_target}/lib
 
   make -C libcpp DESTDIR="${pkgdir}" install
-
-  # Fortran
-  make -C $_target/libgfortran DESTDIR=$pkgdir install-{{caf,my}execlibLTLIBRARIES,toolexeclibDATA}
-  make -C $_target/libgomp DESTDIR=$pkgdir install-nodist_fincludeHEADERS
-  make -C gcc DESTDIR=$pkgdir fortran.install-{common,man,info}
-
-  # old gcc
-  make DESTDIR="$pkgdir" install-gcc install-target-libgcc \
-       install-target-libstdc++-v3
-
   rm "$pkgdir"/usr/lib/libiberty.a
-  rm -rf "$pkgdir"/usr/share/{man/man7,info}/
-
-  cp -r "$pkgdir"/usr/libexec/* "$pkgdir/usr/lib/"
-  rm -rf "$pkgdir/usr/libexec"
-
-  rm -rf "$pkgdir/usr/share/gcc-${pkgver}/python"
-
-  # strip it manually
-  strip "$pkgdir"/usr/bin/* 2>/dev/null || true
-  find "$pkgdir"/usr/lib -type f -exec /usr/bin/${_target}-strip \
-       --strip-unneeded {} \; 2>/dev/null || true
 }
+
+package_gcc-fortran() {
+  setup_env
+  pkgdesc="Fortran front-end for GCC (${_target})"
+  depends=("${_target}-gcc=$pkgver-$pkgrel")
+
+  cd gcc-build
+  make -C $_target/libgfortran DESTDIR="$pkgdir" \
+       install-{caf,my}execlibLTLIBRARIES \
+       install-{toolexeclibDATA,nodist_fincludeHEADERS}
+  make -C $_target/libgomp DESTDIR="$pkgdir" install-nodist_fincludeHEADERS
+  make -C gcc DESTDIR="$pkgdir" fortran.install-common
+
+  install -Dm755 gcc/f951 $pkgdir/${_libdir}/f951
+}
+
+package_gcc-objc() {
+  setup_env
+  pkgdesc="Objective-C front-end for GCC (${_target})"
+  depends=("${_target}-gcc=$pkgver-$pkgrel")
+
+  cd gcc-build
+  make DESTDIR="$pkgdir" -C $_target/libobjc install-headers
+  install -dm755 "$pkgdir"/${_libdir}
+  install -m755 gcc/cc1obj{,plus} "$pkgdir"/${_libdir}/
+}
+
+package_gcc-go() {
+  setup_env
+  pkgdesc="Go front-end for GCC (${_target})"
+  depends=("${_target}-gcc=$pkgver-$pkgrel")
+
+  cd gcc-build
+  make -C $_target/libgo DESTDIR="$pkgdir" install-exec-am
+  make -C gcc DESTDIR=$pkgdir go.install-common
+  install -Dm755 gcc/go1 $pkgdir/${_libdir}/go1
+
+  make DESTDIR=${pkgdir} install-gotools
+}
+
+pkgname=()
+for pkg in "${_pkgname[@]}"; do
+  pkgname=("${pkgname[@]}" "${_target}-${pkg}")
+  eval "package_${_target}-${pkg}() {
+    package_${pkg}
+}"
+done
+
+# package() {
+#   cd gcc-build
+
+#   # old gcc
+#   make DESTDIR="$pkgdir" install-gcc install-target-libgcc \
+#        install-target-libstdc++-v3
+
+#   rm "$pkgdir"/usr/lib/libiberty.a
+#   rm -rf "$pkgdir"/usr/share/{man/man7,info}/
+
+#   cp -r "$pkgdir"/usr/libexec/* "$pkgdir/usr/lib/"
+#   rm -rf "$pkgdir/usr/libexec"
+
+#   rm -rf "$pkgdir/usr/share/gcc-${pkgver}/python"
+
+#   # strip it manually
+#   strip "$pkgdir"/usr/bin/* 2>/dev/null || true
+#   find "$pkgdir"/usr/lib -type f -exec /usr/bin/${_target}-strip \
+#        --strip-unneeded {} \; 2>/dev/null || true
+# }
