updpkg:lxd 2.19-2

diff --git a/lxd/PKGBUILD b/lxd/PKGBUILD
--- a/lxd/PKGBUILD
+++ b/lxd/PKGBUILD
@@ -2,8 +2,8 @@
 # Contributor: Benjamin Asbach <archlinux-aur.lxd@impl.it>
 
 pkgname=lxd
-pkgver=2.17
-pkgrel=1
+pkgver=2.19
+pkgrel=2
 pkgdesc="REST API, command line tool and OpenStack integration plugin for LXC."
 arch=('x86_64')
 url="https://github.com/lxc/lxd"
@@ -30,7 +30,7 @@ source=(
     "networkmanager-dnsmasq-lxd.conf"
 )
 
-md5sums=('179ccae9b1870538dff8629c079974f8'
+md5sums=('e9a59a5255287d50be7d9e2f7d87e1bb'
          '5dde136f2fbcdf5773a011a39c82cfc6'
          'b1fd16933c1b24aaa9ccc8f5a0e6478c'
          '15ae1bc51684d611bded2839ca55a37b'
@@ -38,56 +38,54 @@ md5sums=('179ccae9b1870538dff8629c079974f8'
          'c86b8c441ab014340186acc7799096f2'
          '427926fddb1537f7a65d0a7274106df5')
 
-_gourl=github.com/lxc/lxd
-
-
 build() {
-  mkdir -p $srcdir/src/${_gourl}
-  cp -r --preserve=timestamps $srcdir/$pkgname-$pkgname-$pkgver/* $srcdir/src/${_gourl}/
-  cd $srcdir/src/${_gourl}
-  # This git config fix is a workaround for:
-  # https://github.com/niemeyer/gopkg/issues/50
-  git config --global http.https://gopkg.in.followRedirects true
-
-  GOPATH="$srcdir" GOBIN="$srcdir/bin" make
+  export GOPATH="${srcdir}/go"
+  go_base=github.com/lxc/lxd
+  mkdir -p "${GOPATH}"
+  GOPATH="${GOPATH}" go get "${go_base}" || echo "(ignoring go error)"
+  cd "${GOPATH}/src/${go_base}"
+  make
 }
 
 package() {
+  go_bin_dir="${GOPATH}/bin"
   install=lxd.install
-
-  mkdir -p "$pkgdir/usr/bin"
-  mkdir -p "$pkgdir/usr/lib/lxd"
-  mkdir -p "$pkgdir/usr/share/bash-completion/completions"
-
-  install -p -m755 "$srcdir/bin/"* "$pkgdir/usr/bin"
+  mkdir -p "${pkgdir}/usr/bin"
+  mkdir -p "${pkgdir}/usr/lib/lxd"
+  mkdir -p "${pkgdir}/usr/share/bash-completion/completions"
+  install -p -m755 "${go_bin_dir}/"* "${pkgdir}/usr/bin"
 
   # Package license (if available)
   for f in LICENSE COPYING LICENSE.* COPYING.*; do
-    if [ -e "$srcdir/src/$_gourl/$f" ]; then
-      install -Dm644 "$srcdir/src/$_gourl/$f" \
-        "$pkgdir/usr/share/licenses/$pkgname/$f"
+    if [ -e "${go_bin_dir}/$f" ]; then
+      install -Dm644 "${go_bin_dir}/$f" \
+        "${pkgdir}/usr/share/licenses/${pkgname}/$f"
     fi
   done
-
   install -D -m644 "${srcdir}/lxd.service" \
-      "${pkgdir}/usr/lib/systemd/system/lxd.service"
+    "${pkgdir}/usr/lib/systemd/system/lxd.service"
 
   # Bash completions
-  install -p -m755 "$srcdir/$pkgname-$pkgname-$pkgver/config/bash/lxd-client" "$pkgdir/usr/share/bash-completion/completions/lxc"
+  install -p -m755 "${srcdir}/${pkgname}-${pkgname}-${pkgver}/config/bash/lxd-client" \
+    "${pkgdir}/usr/share/bash-completion/completions/lxd"
 
   # Example configuration files
-  mkdir -p "$pkgdir/usr/share/lxd/"
-  mkdir -p "$pkgdir/usr/share/lxd/systemd/system/"
-  mkdir -p "$pkgdir/usr/share/lxd/netctl/"
-  mkdir -p "$pkgdir/usr/share/lxd/dbus-1/system.d/"
-  mkdir -p "$pkgdir/usr/share/lxd/NetworkManager/dnsmasq.d/"
+  mkdir -p "${pkgdir}/usr/share/lxd/"
+  mkdir -p "${pkgdir}/usr/share/lxd/systemd/system/"
+  mkdir -p "${pkgdir}/usr/share/lxd/netctl/"
+  mkdir -p "${pkgdir}/usr/share/lxd/dbus-1/system.d/"
+  mkdir -p "${pkgdir}/usr/share/lxd/NetworkManager/dnsmasq.d/"
 
-  install -Dm644 "${srcdir}/dnsmasq-lxd.conf" "${pkgdir}/usr/share/lxd/dnsmasq-lxd.conf"
-  install -Dm644 "${srcdir}/dnsmasq@lxd.service" "${pkgdir}/usr/share/lxd/systemd/system/dnsmasq@lxd.service"
-  install -Dm644 "${srcdir}/lxd.netctl" "${pkgdir}/usr/share/lxd/netctl/lxd"
-  install -Dm644 "${srcdir}/dbus-dnsmasq-lxd.conf" "${pkgdir}/usr/share/lxd/dbus-1/system.d/dnsmasq-lxd.conf"
-  install -Dm644 "${srcdir}/networkmanager-dnsmasq-lxd.conf" "${pkgdir}/usr/share/lxd/NetworkManager/dnsmasq.d/lxd.conf"
-
+  install -Dm644 "${srcdir}/dnsmasq-lxd.conf" \
+    "${pkgdir}/usr/share/lxd/dnsmasq-lxd.conf"
+  install -Dm644 "${srcdir}/dnsmasq@lxd.service" \
+    "${pkgdir}/usr/share/lxd/systemd/system/dnsmasq@lxd.service"
+  install -Dm644 "${srcdir}/lxd.netctl" \
+    "${pkgdir}/usr/share/lxd/netctl/lxd"
+  install -Dm644 "${srcdir}/dbus-dnsmasq-lxd.conf" \
+    "${pkgdir}/usr/share/lxd/dbus-1/system.d/dnsmasq-lxd.conf"
+  install -Dm644 "${srcdir}/networkmanager-dnsmasq-lxd.conf" \
+    "${pkgdir}/usr/share/lxd/NetworkManager/dnsmasq.d/lxd.conf"
 }
 
 # vim:set ts=2 sw=2 et:
