[proton] Update and follow AUR

diff --git a/archlinuxcn/proton/PKGBUILD b/archlinuxcn/proton/PKGBUILD
--- a/archlinuxcn/proton/PKGBUILD
+++ b/archlinuxcn/proton/PKGBUILD
@@ -1,99 +1,425 @@
-# Maintainer: somebody <ehern.lee@gmail.com>
+# Maintainer: loathingkernel <loathingkernel _a_ gmail _d_ com>
+# Contributor: E-Hern Lee <ehern.lee@gmail.com>
 # Contributor: anon@sansorgan.es
 # Contributor: heavysink <winstonwu91 at gmail>
 
 pkgname=proton
-# Upstream version
-_pkgver='6.3-4'
-# Arch - no hyphens
-pkgver=6.3.4
-pkgrel=1
+_srctag=7.0-1b
+_commit=
+pkgver=7.0.1
+_geckover=2.47.2
+_monover=7.1.2
+_asyncver=1.9.4
+pkgrel=5
+epoch=1
 pkgdesc="Compatibility tool for Steam Play based on Wine and additional components"
-arch=('x86_64')
-url="https://github.com/ValveSoftware/Proton/"
-license=('BSD')
-groups=()
+url="https://github.com/ValveSoftware/Proton"
+arch=(x86_64 x86_64_v3)
+options=(!staticlibs !lto emptydirs)
+license=('custom')
+
 depends=(
-	'wine-valve'
+  attr             lib32-attr
+  fontconfig       lib32-fontconfig
+  lcms2            lib32-lcms2
+  libxml2          lib32-libxml2
+  libxcursor       lib32-libxcursor
+  libxrandr        lib32-libxrandr
+  libxdamage       lib32-libxdamage
+  libxi            lib32-libxi
+  gettext          lib32-gettext
+  freetype2        lib32-freetype2
+  glu              lib32-glu
+  libsm            lib32-libsm
+  gcc-libs         lib32-gcc-libs
+  libpcap          lib32-libpcap
+  lzo              lib32-lzo
+  libxkbcommon     lib32-libxkbcommon
+  faudio           lib32-faudio
+  'sdl2>=2.0.16'   'lib32-sdl2>=2.0.16'
+  desktop-file-utils
+  python
+  steam-native-runtime
 )
-makedepends=(
-	'vulkan-headers'
+
+makedepends=(autoconf bison perl fontforge flex mingw-w64-gcc
+  git wget rsync mingw-w64-tools lld nasm meson cmake python-virtualenv python-pip
+  glslang vulkan-headers
+  clang
+  giflib                lib32-giflib
+  libpng                lib32-libpng
+  gnutls                lib32-gnutls
+  libxinerama           lib32-libxinerama
+  libxcomposite         lib32-libxcomposite
+  libxmu                lib32-libxmu
+  libxxf86vm            lib32-libxxf86vm
+  libldap               lib32-libldap
+  mpg123                lib32-mpg123
+  openal                lib32-openal
+  v4l-utils             lib32-v4l-utils
+  alsa-lib              lib32-alsa-lib
+  libxcomposite         lib32-libxcomposite
+  mesa                  lib32-mesa
+  mesa-libgl            lib32-mesa-libgl
+  opencl-icd-loader     lib32-opencl-icd-loader
+  libxslt               lib32-libxslt
+  libpulse              lib32-libpulse
+  libva                 lib32-libva
+  gtk3                  lib32-gtk3
+  gst-plugins-base-libs lib32-gst-plugins-base-libs
+  vulkan-icd-loader     lib32-vulkan-icd-loader
+  'sdl2>=2.0.16'        'lib32-sdl2>=2.0.16'
+  rust                  lib32-rust-libs
+  libgphoto2
+  gsm
+  opencl-headers
 )
+
+optdepends=(
+  giflib                lib32-giflib
+  libpng                lib32-libpng
+  libldap               lib32-libldap
+  gnutls                lib32-gnutls
+  mpg123                lib32-mpg123
+  openal                lib32-openal
+  v4l-utils             lib32-v4l-utils
+  libpulse              lib32-libpulse
+  alsa-plugins          lib32-alsa-plugins
+  alsa-lib              lib32-alsa-lib
+  libjpeg-turbo         lib32-libjpeg-turbo
+  libxcomposite         lib32-libxcomposite
+  libxinerama           lib32-libxinerama
+  opencl-icd-loader     lib32-opencl-icd-loader
+  libxslt               lib32-libxslt
+  libva                 lib32-libva
+  gtk3                  lib32-gtk3
+  gst-plugins-base-libs lib32-gst-plugins-base-libs
+  vulkan-icd-loader     lib32-vulkan-icd-loader
+  libgphoto2
+  gsm
+  dosbox
+)
+
+makedepends=(${makedepends[@]} ${depends[@]})
+provides=('proton-native')
+conflicts=('proton-native')
+#install=${pkgname}.install
 source=(
-	"https://github.com/ValveSoftware/Proton/archive/$pkgname-$_pkgver.tar.gz"
+    proton::git+https://github.com/ValveSoftware/Proton.git#tag=proton-${_srctag}
+    wine-valve::git+https://github.com/ValveSoftware/wine.git
+    dxvk-valve::git+https://github.com/ValveSoftware/dxvk.git
+    openvr::git+https://github.com/ValveSoftware/openvr.git
+    liberation-fonts::git+https://github.com/liberationfonts/liberation-fonts.git
+    gstreamer::git+https://gitlab.freedesktop.org/gstreamer/gstreamer.git
+    gst-plugins-base::git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-base.git
+    gst-plugins-good::git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-good.git
+    gst-orc::git+https://gitlab.freedesktop.org/gstreamer/orc.git
+    vkd3d-proton::git+https://github.com/HansKristian-Work/vkd3d-proton.git
+    OpenXR-SDK::git+https://github.com/KhronosGroup/OpenXR-SDK.git
+    dxvk-nvapi::git+https://github.com/jp7677/dxvk-nvapi.git
+    vkd3d-valve::git+https://github.com/ValveSoftware/vkd3d.git
+    Vulkan-Headers::git+https://github.com/KhronosGroup/Vulkan-Headers.git
+    SPIRV-Headers::git+https://github.com/KhronosGroup/SPIRV-Headers.git
+    Vulkan-Loader::git+https://github.com/KhronosGroup/Vulkan-Loader.git
+    gst-libav::git+https://gitlab.freedesktop.org/gstreamer/gst-libav.git
+    ffmpeg::git+https://git.ffmpeg.org/ffmpeg.git
+    dav1d::git+https://code.videolan.org/videolan/dav1d.git
+    gst-plugins-rs::git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git
+    dxil-spirv::git+https://github.com/HansKristian-Work/dxil-spirv.git
+    https://dl.winehq.org/wine/wine-gecko/${_geckover}/wine-gecko-${_geckover}-x86{,_64}.tar.xz
+    https://github.com/madewokherd/wine-mono/releases/download/wine-mono-${_monover}/wine-mono-${_monover}-x86.tar.xz
+    dxvk-async-${_asyncver}.patch::https://raw.githubusercontent.com/Sporif/dxvk-async/${_asyncver}/dxvk-async.patch
+    wine-25946b48148784e8275c1685f6498ab88f553ca3.patch
+    wine-futex_waitv.patch
+    wine-winevulkan_fsr.patch
+    wine-more_8x5_res.patch
+    proton-sanitize_makefile.patch
+    proton-disable_lock.patch
+    proton-user_compat_data.patch
+    proton-proton_native_transition.patch
 )
-sha512sums=('b11c0e499bb0816b6fc10e1281773f86fd6f9062c210337ab338192475f4888ae80df93b4ef37ecf7d61e24b540f6ec69cf447cad8a3b5b1bbe5a3674347327c')
+noextract=(
+    wine-gecko-${_geckover}-{x86,x86_64}.tar.xz
+    wine-mono-${_monover}-x86.tar.xz
+)
+
+_make_wrappers () {
+    #     _arch     prefix   gcc    ld             as     strip
+    local _i686=(  "i686"   "-m32" "-melf_i386"   "--32" "elf32-i386")
+    local _x86_64=("x86_64" "-m64" "-melf_x86_64" "--64" "elf64-x86-64")
+    local _opts=(_i686 _x86_64)
+    declare -n _opt
+    for _opt in "${_opts[@]}"; do
+        for l in ar ranlib nm; do
+            ln -s /usr/bin/$l wrappers/${_opt[0]}-pc-linux-gnu-$l
+        done
+        for t in gcc g++; do
+            install -Dm755 /dev/stdin wrappers/${_opt[0]}-pc-linux-gnu-$t <<EOF
+#!/usr/bin/bash
+$(which ccache 2> /dev/null) /usr/bin/$t ${_opt[1]} "\$@"
+EOF
+        done
+        install -Dm755 /dev/stdin wrappers/${_opt[0]}-pc-linux-gnu-ld <<EOF
+#!/usr/bin/bash
+/usr/bin/ld ${_opt[2]} "\$@"
+EOF
+        install -Dm755 /dev/stdin wrappers/${_opt[0]}-pc-linux-gnu-as <<EOF
+#!/usr/bin/bash
+/usr/bin/as ${_opt[3]} "\$@"
+EOF
+        install -Dm755 /dev/stdin wrappers/${_opt[0]}-pc-linux-gnu-strip <<EOF
+#!/usr/bin/bash
+/usr/bin/strip -F ${_opt[4]} "\$@"
+EOF
+    done
+}
 
 prepare() {
-	cd "Proton-$pkgname-$_pkgver"
-  sed -i 's,wined3d-interop.h,wine/wined3d-interop.h,g' vrclient_x64/vrclient_x64/vrclient_main.c
+    # I know this is fugly and it should NOT be done
+    # but the afdko package from AUR breaks regularly.
+    # Install it from pip in a virtualenv
+    [ -d build_venv ] && rm -rf build_venv
+    virtualenv --app-data "$srcdir"/build_venv/cache --no-wheel build_venv
+    source build_venv/bin/activate
+    pip install --no-cache-dir meson==0.59.3
+    pip install --no-cache-dir afdko
+    pip install --no-cache-dir pefile
+
+    # Provide wrappers to compiler tools
+    rm -rf wrappers && mkdir wrappers
+    _make_wrappers
+
+    [ ! -d gecko ] && mkdir gecko
+    mv wine-gecko-${_geckover}-x86{,_64}.tar.xz gecko/
+
+    [ ! -d mono ] && mkdir mono
+    mv wine-mono-${_monover}-x86.tar.xz mono/
+
+    [ ! -d build ] && mkdir build
+    cd proton
+
+    _submodules=(
+        wine-valve::wine
+        dxvk-valve::dxvk
+        openvr
+        liberation-fonts::fonts/liberation-fonts
+        gstreamer
+        gst-plugins-base
+        gst-plugins-good
+        gst-orc
+        vkd3d-proton
+        OpenXR-SDK
+        dxvk-nvapi
+        vkd3d-valve::vkd3d
+        Vulkan-Headers
+        SPIRV-Headers
+        Vulkan-Loader
+        gst-libav
+        ffmpeg
+        dav1d
+        gst-plugins-rs
+    )
+
+    for submodule in "${_submodules[@]}"; do
+        git submodule init "${submodule#*::}"
+        git config submodule."${submodule#*::}".url "$srcdir"/"${submodule%::*}"
+        git submodule update "${submodule#*::}"
+    done
+
+    pushd vkd3d-proton
+        for submodule in subprojects/{dxil-spirv,Vulkan-Headers,SPIRV-Headers}; do
+            git submodule init "${submodule}"
+            git config submodule."${submodule}".url "$srcdir"/"${submodule#*/}"
+            git submodule update "${submodule}"
+        done
+        pushd subprojects/dxil-spirv
+            git submodule init third_party/spirv-headers
+            git config submodule.third_party/spirv-headers.url "$srcdir"/SPIRV-Headers
+            git submodule update third_party/spirv-headers
+        popd
+    popd
+
+    pushd dxvk-nvapi
+        git submodule init external/Vulkan-Headers
+        git config submodule.external/Vulkan-Headers.url "$srcdir"/Vulkan-Headers
+        git submodule update external/Vulkan-Headers
+    popd
+
+    for submodule in gst-plugins-rs media-converter; do
+    pushd $submodule
+        export RUSTUP_TOOLCHAIN=stable
+        export CARGO_HOME="${srcdir}"/build/.cargo
+        cargo update
+        cargo fetch --locked --target "i686-unknown-linux-gnu"
+        cargo fetch --locked --target "x86_64-unknown-linux-gnu"
+    popd
+    done
+
+    pushd wine
+        # From Arch Wine
+        sed 's|OpenCL/opencl.h|CL/opencl.h|g' -i configure*
+        # Fix openldap 2.5+ detection
+        sed 's/-lldap_r/-lldap/' -i configure
+        # Fix wldap32 compilation on 32bit
+        patch -p1 -i "$srcdir"/wine-25946b48148784e8275c1685f6498ab88f553ca3.patch
+        # Fix futex_waitv on recent linux-api-headers
+        patch -p1 -i "$srcdir"/wine-futex_waitv.patch
+        # Add FSR for fshack
+        patch -p1 -i "$srcdir"/wine-winevulkan_fsr.patch
+        # Adds more 16:10 resolutions for use with FSR
+        patch -p1 -i "$srcdir"/wine-more_8x5_res.patch
+    popd
+
+    pushd dxvk
+        # Uncomment to enable dxvk async patch.
+        # Enable at your own risk. If you don't know what it is,
+        # and its implications, leave it as is. You have been warned.
+        # I am not liable if anything happens to you by using it.
+        patch -p1 -i "$srcdir"/dxvk-async-${_asyncver}.patch
+    popd
+
+    patch -p1 -i "$srcdir"/proton-sanitize_makefile.patch
+    patch -p1 -i "$srcdir"/proton-disable_lock.patch
+    patch -p1 -i "$srcdir"/proton-user_compat_data.patch
+
+    # Remove repos from srcdir to save space
+    for submodule in "${_submodules[@]}"; do
+        rm -rf "$srcdir"/"${submodule%::*}"
+    done
+    rm -rf "$srcdir"/dxil-spirv
+    rm -rf "$srcdir"/Vulkan-Headers
+    rm -rf "$srcdir"/SPIRV-Headers
 }
 
 build() {
-	cd "Proton-$pkgname-$_pkgver"
+    source build_venv/bin/activate
+    export PATH="$(pwd)/wrappers:$PATH"
 
-	export CXXFLAGS="$CXXFLAGS -Wno-attributes"
-	export WINEMAKEFLAGS="--nosource-fix --nolower-include --nodlls --nomsvcrt --dll -ldl"
-	export WINEMAKEFLAGS32="$WINEMAKEFLAGS --wine32"
-  export LDFLAGS="$LDFLAGS -L/usr/lib32/wine -lntdll.dll"
+    cd build
+    ROOTLESS_CONTAINER="" \
+    ../proton/configure.sh \
+        --container-engine="none" \
+        --proton-sdk-image="" \
+        --steam-runtime=native \
+        --no-proton-sdk \
+        --build-name="${pkgname}"
 
-	# The build script provided has so much cruft that it's easier to make everything manually
-	mkdir -p build/lsteamclient.win32
-	cp -a lsteamclient/* build/lsteamclient.win32
-	cd build/lsteamclient.win32
-	winemaker $WINEMAKEFLAGS32 -DSTEAM_API_EXPORTS .
-	make
-	cd ../..
-	
-	mkdir -p build/lsteamclient.win64
-	cp -a lsteamclient/* build/lsteamclient.win64
-	cd build/lsteamclient.win64
-	winemaker $WINEMAKEFLAGS -DSTEAM_API_EXPORTS .
-	make
-	cd ../..
+    # Filter known bad flags before applying optimizations
+    # Filter fstack-protector{ ,-all,-strong} flag for MingW.
+    # https://github.com/Joshua-Ashton/d9vk/issues/476
+    export CFLAGS="${CFLAGS// -fstack-protector*([\-all|\-strong])/}"
+    export CXXFLAGS="${CXXFLAGS// -fstack-protector*([\-all|\-strong])/}"
+    # From wine-staging PKGBUILD
+    # Doesn't compile with these flags in MingW so remove them.
+    # They are also filtered in Wine PKGBUILDs so remove them
+    # for winelib versions too.
+    # Doesn't compile without remove these flags as of 4.10
+    export CFLAGS="${CFLAGS/ -fno-plt/}"
+    export CXXFLAGS="${CXXFLAGS/ -fno-plt/}"
+    export LDFLAGS="${LDFLAGS/,-z,now/}"
+    # MingW Wine builds fail with relro
+    export LDFLAGS="${LDFLAGS/,-z,relro/}"
 
-	# Currently depends on the custom bundled wine
-	mkdir -p build/vrclient.win32
-	cp -a vrclient_x64/* build/vrclient.win32
-	rm -rf build/vrclient.win32/vrclient
-	mv build/vrclient.win32/vrclient_x64 build/vrclient.win32/vrclient
-	cd build/vrclient.win32/vrclient
-	mv -u vrclient_x64.spec vrclient.spec
-	winemaker -I.. $WINEMAKEFLAGS32 .
-	CXXFLAGS="$CXXFLAGS --std=c++0x" make
-	winebuild --dll --fake-module -E vrclient.spec -o vrclient.dll.fake
-	cd ../../..
+    # By default export FLAGS used by proton and ignore makepkg
+    # This overrides FLAGS from makepkg.conf, if you comment these you are on your own
+    # If you want the "best" possible optimizations for your system you can use
+    # `-march=native` and remove the `-mtune=core-avx2` option.
+    # `-O2` is adjusted to `-O3` since AVX is disabled
+    export CFLAGS="-O3 -march=nocona -mtune=core-avx2 -pipe"
+    export CXXFLAGS="-O3 -march=nocona -mtune=core-avx2 -pipe"
+    export RUSTFLAGS="-C opt-level=3 -C target-cpu=nocona"
+    export LDFLAGS="-Wl,-O1,--sort-common,--as-needed"
 
-	mkdir -p build/vrclient.win64
-	cp -a vrclient_x64/* build/vrclient.win64
-	cd build/vrclient.win64/vrclient_x64
-	winemaker -I.. $WINEMAKEFLAGS .
-	CXXFLAGS="$CXXFLAGS --std=c++0x" make
-	winebuild --dll --fake-module -E vrclient_x64.spec -o vrclient_x64.dll.fake
+    # If using -march=native and the CPU supports AVX, launching a d3d9
+    # game can cause an Unhandled exception. The cause seems to be the
+    # combination of AVX instructions and tree vectorization (implied by O3),
+    # all tested archictures from sandybridge to haswell are affected.
+    # Since Wine 5.16 AVX is supported. Testing showed 32bit applications
+    # crashing with AVX regardless, but 64bit applications worked just fine.
+    # Relevant Wine issues
+    # https://bugs.winehq.org/show_bug.cgi?id=45289
+    # https://bugs.winehq.org/show_bug.cgi?id=43516
+    # AVX is "hard" disabled for 32bit in any case.
+    # AVX2 for 64bit is disabled below.
+    export CFLAGS+=" -mno-avx2"
+    export CXXFLAGS+=" -mno-avx2"
+
+    export RUSTUP_TOOLCHAIN=stable
+    export WINEESYNC=0
+    export WINEFSYNC=0
+    export DISPLAY=
+    SUBJOBS=$([[ "$MAKEFLAGS" =~ -j\ *([1-9][0-9]*) ]] && echo "${BASH_REMATCH[1]}" || echo "$(nproc)") \
+        make -j1 dist
 }
 
 package() {
-	cd "Proton-$pkgname-$_pkgver"
-	
-	install -d -m755 $pkgdir/usr/share/licenses/$pkgname
-	install -m644 LICENSE $pkgdir/usr/share/licenses/$pkgname/LICENSE
-	install -m644 LICENSE.proton $pkgdir/usr/share/licenses/$pkgname/LICENSE.proton
-	install -m644 dist.LICENSE $pkgdir/usr/share/licenses/$pkgname/dist.LICENSE
+    cd build
 
-	install -d -m755 $pkgdir/usr/share/doc/$pkgname
-	install -m644 README.md $pkgdir/usr/share/doc/$pkgname/README.md
+    local _compatdir="$pkgdir/usr/share/steam/compatibilitytools.d"
+    mkdir -p "$_compatdir"
+    cp -rf --no-dereference --preserve=mode,links dist "$_compatdir/${pkgname}"
 
-	install -d -m755 $pkgdir/usr/lib32/wine
-	install -m755 build/lsteamclient.win32/lsteamclient.dll.so $pkgdir/usr/lib32/wine/
-	install -m755 build/vrclient.win32/vrclient/vrclient.dll.so $pkgdir/usr/lib32/wine/
+    mkdir -p "$pkgdir/usr/share/licenses/${pkgname}"
+    mv "$_compatdir/${pkgname}"/LICENSE{,.OFL} \
+        "$pkgdir/usr/share/licenses/${pkgname}"
 
-	install -d $pkgdir/usr/lib32/wine/fakedlls
-	install -m644 build/vrclient.win32/vrclient/vrclient.dll.fake $pkgdir/usr/lib32/wine/fakedlls/vrclient.dll
+    cd "$_compatdir/${pkgname}/dist"
+    i686-w64-mingw32-strip --strip-unneeded \
+        $(find lib/wine \( -iname fakedlls -or -iname i386-windows \) -prune -false -or -iname "*.dll" -or -iname "*.exe")
+    x86_64-w64-mingw32-strip --strip-unneeded \
+        $(find lib64/wine \( -iname fakedlls -or -iname x86_64-windows \) -prune -false -or -iname "*.dll" -or -iname "*.exe")
 
-	install -d -m755 $pkgdir/usr/lib/wine
-	install -m755 build/lsteamclient.win64/lsteamclient.dll.so $pkgdir/usr/lib/wine/
-	install -m755 build/vrclient.win64/vrclient_x64/vrclient_x64.dll.so $pkgdir/usr/lib/wine/
+    local _geckodir="share/wine/gecko/wine-gecko-${_geckover}"
+    i686-w64-mingw32-strip --strip-unneeded \
+        $(find "$_geckodir"-x86 -iname "*.dll" -or -iname "*.exe")
+    x86_64-w64-mingw32-strip --strip-unneeded \
+        $(find "$_geckodir"-x86_64 -iname "*.dll" -or -iname "*.exe")
 
-	install -d $pkgdir/usr/lib/wine/fakedlls
-	install -m644 build/vrclient.win64/vrclient_x64/vrclient_x64.dll.fake $pkgdir/usr/lib/wine/fakedlls/vrclient_x64.dll
+    local _monodir="share/wine/mono/wine-mono-${_monover}"
+    i686-w64-mingw32-strip --strip-unneeded \
+        $(find "$_monodir"/lib/mono -iname "*.dll" -or -iname "*.exe")
+    i686-w64-mingw32-strip --strip-unneeded \
+        "$_monodir"/lib/x86/*.dll \
+        $(find "$_monodir" -iname "*x86.dll" -or -iname "*x86.exe")
+    x86_64-w64-mingw32-strip --strip-unneeded \
+        "$_monodir"/lib/x86_64/*.dll \
+        $(find "$_monodir" -iname "*x86_64.dll" -or -iname "*x86_64.exe")
+
+    cd "$_compatdir/${pkgname}"
+    # Add old tool name in compatibilitytool.vdf
+    patch -p1 -i "$srcdir"/proton-proton_native_transition.patch
 }
+
+sha256sums=('SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            'SKIP'
+            '8fab46ea2110b2b0beed414e3ebb4e038a3da04900e7a28492ca3c3ccf9fea94'
+            'b4476706a4c3f23461da98bed34f355ff623c5d2bb2da1e2fa0c6a310bc33014'
+            '59f146dde0f0540ca4648fc648e6b16335c71921deaf111b5fe8c3967881661d'
+            'ddde07c98045a3bc15fab5eaf3c6a756a6a4b4eaeec646d4339168b86ac00463'
+            '11aa65bb6b8da1814557edf18a3cdada80135b021634236feabf93d2a194838b'
+            '7d989e9b29643897eaadb970d65e71140b11f4d641ef8816bd17feb9ad2ca992'
+            'd76b87410047f623accc846f15f849fe13275924c685ccfb95a91a8b22943e51'
+            '9005d8169266ba0b93be30e1475fe9a3697464796f553886c155ec1d77d71215'
+            'daa595cfb1d661c48df6ddf832b743ad14265c06da98fcd91484b4b011f5f10e'
+            '215da4b34e00c060dcc7a4f1d526769330e28416305f4b12949affeeec994408'
+            '3cebd3d1bc920bcfacb7b0dfe2bdf386bdb9c031317e7f7b45148853b618ed78'
+            '958f8e69bc789cc8fbe58cb6c9fc62f065692c3c165f20b0c21133ce94bad736')
