auto update for package anaconda

diff --git a/anaconda/installer_sh_x86.patch b/anaconda/installer_sh_x86.patch
--- a/anaconda/installer_sh_x86.patch
+++ b/anaconda/installer_sh_x86.patch
@@ -1,32 +1,32 @@
---- a/Anaconda3-2.4.1-Linux-x86.sh	2015-12-14 20:11:17.819411594 +0100
-+++ b/Anaconda3-2.4.1-Linux-x86.sh	2015-12-14 20:12:39.158562465 +0100
+--- a/Anaconda3-2.5.0-Linux-x86.sh	2016-02-22 12:30:56.081446621 +0100
++++ b/Anaconda3-2.5.0-Linux-x86.sh	2016-02-22 12:32:36.550378227 +0100
 @@ -73,9 +73,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 265518790 >/dev/null
-+wc -c "$THIS_PATH" | grep 265518797 >/dev/null
+-wc -c "$THIS_PATH" | grep 350634167 >/dev/null
++wc -c "$THIS_PATH" | grep 350634174 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 265518790 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 265518797 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 350634167 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 350634174 bytes" >&2
      exit 1
  fi
  
-@@ -426,7 +426,7 @@
- extract_dist anaconda-2.4.1-np110py35_0
+@@ -433,7 +433,7 @@
+ extract_dist conda-env-2.4.5-py35_0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-3.5.1-0/bin/python -E"
- $PYTHON -V
-@@ -436,7 +436,7 @@
+ PYTHON="$PREFIX/pkgs/python-3.5.1-0/bin/python"
+ $PYTHON -E -V
+@@ -443,7 +443,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.18.8-py35_0/lib/python3.5/site-packages/conda/install.py"
- $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.19.1-py35_0/lib/python3.5/site-packages/conda/install.py"
+ $PYTHON -E -s $CONDA_INSTALL --prefix=$PREFIX --file=conda-meta/.ilan || exit 1
diff --git a/anaconda/installer_sh_x86_64.patch b/anaconda/installer_sh_x86_64.patch
--- a/anaconda/installer_sh_x86_64.patch
+++ b/anaconda/installer_sh_x86_64.patch
@@ -1,32 +1,32 @@
---- a/Anaconda3-2.4.1-Linux-x86_64.sh	2015-12-14 20:11:17.672746459 +0100
-+++ b/Anaconda3-2.4.1-Linux-x86_64.sh	2015-12-14 20:14:09.677617530 +0100
+--- a/Anaconda3-2.5.0-Linux-x86_64.sh	2016-02-22 12:30:55.911448429 +0100
++++ b/Anaconda3-2.5.0-Linux-x86_64.sh	2016-02-22 12:33:42.666341829 +0100
 @@ -70,9 +70,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 283797156 >/dev/null
-+wc -c "$THIS_PATH" | grep 283797163 >/dev/null
+-wc -c "$THIS_PATH" | grep 414838933 >/dev/null
++wc -c "$THIS_PATH" | grep 414838940 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 283797156 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 283797163 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 414838933 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 414838940 bytes" >&2
      exit 1
  fi
  
-@@ -427,7 +427,7 @@
- extract_dist anaconda-2.4.1-np110py35_0
+@@ -434,7 +434,7 @@
+ extract_dist conda-env-2.4.5-py35_0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-3.5.1-0/bin/python -E"
- $PYTHON -V
-@@ -437,7 +437,7 @@
+ PYTHON="$PREFIX/pkgs/python-3.5.1-0/bin/python"
+ $PYTHON -E -V
+@@ -444,7 +444,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.18.8-py35_0/lib/python3.5/site-packages/conda/install.py"
- $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.19.1-py35_0/lib/python3.5/site-packages/conda/install.py"
+ $PYTHON -E -s $CONDA_INSTALL --prefix=$PREFIX --file=conda-meta/.ilan || exit 1
