upgpkg: downgrade 4.1-1

diff --git a/downgrade/downgrade b/downgrade/downgrade
--- a/downgrade/downgrade
+++ b/downgrade/downgrade
@@ -5,28 +5,34 @@
 # downgrade one or more packages from cache or A.R.M.
 #
 ###
-errorout() { echo "error: $*" >&2; exit 1; }
+TEXTDOMAINDIR=/usr/share/locale
+TEXTDOMAIN=downgrade
+errorout() { echo $"error: $*" >&2; exit 1; }
 
 message() {
   local exit_code="${1:-0}"
 
-  cat << EOF
-
-  usage: downgrade [ -d <dir> ] [ -m <32|64> ] [ -a | -c ] [ -i ] [ -- ] <pkg> ...
+echo $"usage: downgrade [ -d <dir> ] [ -m <i686|x86_64> ] [ -a | -c ] [ -i ] [ -- ] <pkg> ...
     options:
       -d,--pkgdir       set download directory (A.R.M. only), default is \`/tmp'
       -m,--arch         set search architecture (A.R.M. only), default is determined by \`uname -m\`
       -a,--noarm        don't search the A.R.M. when nothing's available in cache
       -c,--nocache      don't look in cache, go directly to A.R.M.
       -i,--noinstalled  don't show [installed] next to installed versions (speed up)
-      -s,--nosudo       don't use sudo, even when available
-
-EOF
+      -s,--nosudo       don't use sudo, even when available"
 
   exit $exit_code
 }
 
-enabled_repos() { sed '/^\[\(.*\)\]$/!d;s//\1/g;/options/d' /etc/pacman.conf; } 
+enabled_repos() { sed '/^\[\(.*\)\]$/!d;s//\1/g;/options/d' /etc/pacman.conf; }
+
+pacman_cache() {
+  local cache
+
+  read -r cache < <(sed '/^ *CacheDir *= *\(.*\)$/!d;s//\1/' /etc/pacman.conf)
+
+  echo "${cache:-/var/cache/pacman/pkg/}"
+}
 
 is_valid_index() {
   local i="$1"; shift
@@ -41,7 +47,7 @@ is_valid_index() {
 # uses sudo or su to root depending on availability and configuration
 as_root() {
   if ! (( $UID )); then
-    errorout 'please do not run downgrade as root; su/sudo will be used when needed'
+    errorout $"please do not run downgrade as root; su/sudo will be used when needed"
   fi
 
   if $usesudo && type -p sudo &>/dev/null; then
@@ -58,18 +64,20 @@ prompt_with_quit() {
   local var="$1" msg="$2"
 
   echo
-  read -r -p "$msg or [q]uit: " $var
+  read -r -p $"$msg or [q]uit: " $var
 
-  [[ "${!var}" == 'q' ]] && exit 1
+  [[ "${!var}" == $"q" ]] && exit 1
 }
 
 prompt_yn() {
-  local msg="$*" ans
+  local msg="$*" ans ques=$"y"
 
   echo
-  read -r -p "$msg? [y/n] " ans
+  read -r -p "$msg? [$ques/$"n"] " ans
+  ans=$(echo $ans |tr '[A-Z]' '[a-z]')
 
-  [[ $ans =~ ^(y|Y) ]]
+  [[ $ans =~ ^($ques) ]]
+  
 }
 
 # we use the $term-[0-9]* glob to disambiguate cases like foo-1.0 and
@@ -78,21 +86,16 @@ local_packages() {
   local term="$1"
 
   # the R is a special case for erlang, others may exist
-  find /var/cache/pacman/pkg -name "$term-[0-9R]*.pkg.tar.[gx]z" | LC_ALL='C' sort -rV
+  find "$(pacman_cache)" -name "$term-[0-9R]*.pkg.tar.[gx]z" | LC_ALL='C' sort -rV
 }
 
 # removes packages duplicated between testing and non-testing repos.
 arm_packages() {
   local term="$1" repos repo url tmp entry pack
 
-  repos=
-  for repo in $(enabled_repos); do
-    repos="${repos}&${repo}=1"
-  done
+  url="http://repo-arm.archlinuxcn.org/search?arch=$arch&pkgname=$term"
 
-  url="http://arm.konnichi.com/search/raw.php?a=$arch&q=%5E$term%24$repos"
-
-  tmp=( $(curl --silent --fail "$url" | grep -v sig$ | sort -rV) )
+  tmp=( $(curl --silent --fail "$url" | grep -v sig$ | cut -d '|' -f 5 | sort -rV) )
 
   for entry in "${tmp[@]}"; do
     read -r repo pack < <(format_arm "$entry")
@@ -119,7 +122,7 @@ print_table() {
 
     i=$((i+1))
     case $pack in
-      ${installed// /-}*) printf "$fmt" "$i" "$repo" "$pack [installed]" ;;
+      ${installed// /-}*) printf "$fmt" "$i" "$repo" $"$pack [installed]" ;;
       *)                  printf "$fmt" "$i" "$repo" "$pack" ;;
     esac
   done
@@ -134,7 +137,7 @@ install_pkg() {
   local pkg="$1"
   local pacman="${PACMAN:-pacman}"
 
-  as_root "$pacman" -U "$pkg" || errorout "could not install package $pkg"
+  as_root "$pacman" -U "$pkg" || errorout $"could not install package $pkg"
 }
 
 # if a choice is made, installs the package.
@@ -147,22 +150,22 @@ check_local_packages() {
   (( ${#locals[@]} )) || return 1
 
   echo
-  echo 'The following packages are available in your cache:'
+  echo $"The following packages are available in your cache:"
   echo
 
   print_table format_local "${locals[@]}"
 
   if $searcharm; then
-    prompt_with_quit num 'please choose a version, [s]earch A.R.M'
+    prompt_with_quit num $"please choose a version, [s]earch A.R.M"
   else
-    prompt_with_quit num 'please choose a version'
+    prompt_with_quit num $"please choose a version"
   fi
 
-  [[ "$num" = 's' ]] && return 1
+  [[ "$num" = $"s" ]] && return 1
 
   n=$((num-1))
 
-  is_valid_index "$n" "${locals[@]}" || errorout 'invalid choice.'
+  is_valid_index "$n" "${locals[@]}" || errorout $"invalid choice."
   install_pkg "${locals[$n]}"
 }
 
@@ -170,7 +173,7 @@ check_local_packages() {
 check_arm_packages() {
   $searcharm || return 1
 
-  [[ "$arch" =~ ^(32|64)$ ]] || errorout "$arch is invalid, must be 32 or 64"
+  [[ "$arch" =~ ^(i686|x86_64)$ ]] || errorout $"$arch is invalid, must be 32 or 64"
 
   local term="$1" url pkg n
   local arms=( $(arm_packages "$term") )
@@ -178,22 +181,22 @@ check_arm_packages() {
   (( ${#arms[@]} )) || return 1
 
   echo
-  echo 'The following packages are available from the A.R.M.:'
+  echo $"The following packages are available from the A.R.M.:"
   echo
 
   print_table format_arm "${arms[@]}"
 
-  prompt_with_quit num 'please choose a version'
+  prompt_with_quit num $"please choose a version"
 
   n=$((num-1))
 
-  is_valid_index "$n" "${arms[@]}" || errorout 'invalid choice.'
+  is_valid_index "$n" "${arms[@]}" || errorout $"invalid choice."
 
   url=${arms[$n]}
   pkg="$pkgdir/$(basename $url)"
 
   if [[ ! -d "$pkgdir" ]]; then
-    mkdir -p "$pkgdir" || errorout "unable to create $pkgdir"
+    mkdir -p "$pkgdir" || errorout $"unable to create $pkgdir"
   fi
 
   curl -# "$url" > "$pkg" || errorout "failed downloading $url"
@@ -204,11 +207,12 @@ check_arm_packages() {
 # onto the end of the IgnorePkg line (iff not already present).
 prompt_to_ignore() {
   local pkg="$1" ans
+  ans=$(echo $ans |tr '[A-Z]' '[a-z]')
   local pacman_conf="${PACMAN_CONF:-/etc/pacman.conf}"
 
   # don't even prompt if already present
   if ! grep -Eq "^IgnorePkg.*( |=)$pkg( |$)" "$pacman_conf"; then
-    if prompt_yn "Add $pkg to IgnorePkg in $pacman_conf"; then
+    if prompt_yn $"Add $pkg to IgnorePkg in $pacman_conf"; then
       as_root sed -i "s/^IgnorePkg.*/& $pkg/" "$pacman_conf"
     fi
   fi
@@ -225,7 +229,7 @@ searchcache=true   # check in cache before arm
 showinstalled=true # show [installed] next to installed versions
 usesudo=true       # use sudo if present
 
-[[ "$(uname -m)" = 'x86_64' ]] && arch=64 || arch=32
+arch=$(uname -m)
 
 # Options
 while [[ -n "$1" ]]; do
