[julia-git] debug source file path

diff --git a/archlinuxcn/julia-git/PKGBUILD b/archlinuxcn/julia-git/PKGBUILD
--- a/archlinuxcn/julia-git/PKGBUILD
+++ b/archlinuxcn/julia-git/PKGBUILD
@@ -130,7 +130,7 @@ prepare() {
 
   for p in cc c++ gcc g++; do
     cat > bin/$p <<EOF
-exec /usr/bin/$p "\${@/#-O0/-Og}" -fasynchronous-unwind-tables
+exec /usr/bin/$p "\${@/#-O0/-Og}" -fasynchronous-unwind-tables -ffile-prefix-map=${srcdir}=${DBGSRCDIR:-/usr/src/debug}
 EOF
     chmod +x bin/$p
   done
@@ -264,18 +264,24 @@ package-julia-in() {
   dbgsrcdir="${DBGSRCDIR:-/usr/src/debug}"
   for binary in usr/bin/julia usr/bin/julia-debug \
                               usr/lib/libjulia.so usr/lib/libjulia-debug.so \
-                              usr/lib/libjulia-internal.so usr/lib/libjulia-internal-debug.so; do
+                              usr/lib/julia/libjulia-internal.so \
+                              usr/lib/julia/libjulia-internal-debug.so; do
     binary="${pkgdir}/${binary}"
+    ls "$binary"
     # copy source files to debug directory
     local f t
     while IFS= read -r t; do
       f=${t/${dbgsrcdir}/"$srcdir"}
-      mkdir -p  "${pkgdir}/${t%/*}"
+      if ! [[ -f "$f" ]]; then
+        echo "Cannot find source file: $f"
+        continue
+      fi
+      mkdir -p "${pkgdir}/${t%/*}"
       cp -- "$f" "${pkgdir}/${t%/*}"
     done < <(_source_files "$binary")
   done
   # Files that are not compiled directly aren't being copied by the code above.
-  # This include all headers as well as come cpp files
+  # This include all headers as well as some cpp files
   #   (e.g. `cgutils.cpp`, `processor_*.cpp` etc)
   # that are included from other files. Copy these directly for now.
   cp src/*.{c,cpp} "${pkgdir}/${dbgsrcdir}/julia/src/"
