[panoply] Upd to 4.12.13. Due to safety for lilac, let lilac generate checksum and check the generated checksum in prepare process in PKGBUILD.

diff --git a/archlinuxcn/panoply/PKGBUILD b/archlinuxcn/panoply/PKGBUILD
--- a/archlinuxcn/panoply/PKGBUILD
+++ b/archlinuxcn/panoply/PKGBUILD
@@ -8,8 +8,7 @@ url='http://www.giss.nasa.gov/tools/panoply/'
 license=('custom')
 groups=('nasa-tools')
 depends=('java-runtime>=9'
-         'hicolor-icon-theme'
-         'desktop-file-utils')
+         'hicolor-icon-theme')
 makedepends=('unzip')
 optdepends=()
 provides=()
@@ -29,8 +28,7 @@ source=("http://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-${pkgver}.zip"
         'panoply128.png'
         'panoply.desktop')
 noextract=()
-_sha1="$(curl https://www.giss.nasa.gov/tools/panoply/download/Panoply-${pkgver}.sha1.txt 2>/dev/null | grep 'PanoplyJ.*.zip' | grep -o '^[^ ]*')"
-sha1sums=("${_sha1}"
+sha1sums=('0ae5b6bbea4f0a6a1a775a0e328d8cc491632324'
           'a83855747414873269e21aaff1a53d13ab5de304'
           '707208d062922b5426303238870e0dd269257697'
           '97c70755c7d87217556de5b2f1012b3be0d375fb'
@@ -41,6 +39,13 @@ sha1sums=("${_sha1}"
           '39c9a58c25d8f764c928e9dfe75f4f73bb9198f0')
 
 prepare() {
+    _sha1="$(curl https://www.giss.nasa.gov/tools/panoply/download/Panoply-${pkgver}.sha1.txt 2>/dev/null | grep 'PanoplyJ.*.zip' | grep -o '^[^ ]*')"
+    if [ "${sha1sums[0]}" = "$_sha1" ]; then
+        echo "Checksum correct. Proceed to build"
+    else
+        echo "Checksum fail. Please check download!"
+        exit 1
+    fi
     cd ${srcdir}/PanoplyJ
     patch -uN -i ../panoply-script.patch || return 1
     unzip -px jars/Panoply.jar gov/nasa/giss/panoply/about/panoply.png > ../panoply192.png
